num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
sum = (num1) + (num2)
print("The sum is:", sum)
print("The difference is:", num1 - num2)
print("The multiplication is:", num1 * num2)
print("The division is:", num1 / num2)
print("The modulus is:", num1 % num2)
print("The floor division is:", num1 // num2)
print("The exponentiation is:", num1 ** num2)